services:
  - type: web
    name: revops-ai
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: SOLANA_WALLET
        value: GEBi3nkeevhWCbRP9zJRBy4uzprKbVEBiM87eHpmk4Ci
